### PR TITLE
SetGameModes

### PR DESCRIPTION
**Pull request by Tiogaplanet**
Added functions to enable each of the game modes available and boolean checkers to make sure game mode was enabled.

### CODE REVIEW

**Review by adamgreen — APPROVED** [review]
Looks great!

I will download updates later today and test them out on my MiP.

**Comment by adamgreen** [comment]
@Tiogaplanet Are there any secrets to getting the MiP to successfully enter a mode other than Cage? When I run your sample, I see that it successfully enters Cage mode and then starts running around my floor in circles but it never indicates that it enters any other mode. My serial output from a 1 minute run:
```
EnableGameMode.ino - Cycles through each mode available.
MiP: Response timeout
MiP: Response timeout
Cage mode enabled.
MiP: Response timeout
MiP: Response timeout
MiP: Response timeout
MiP: Response timeout
MiP: Response timeout
MiP: Response timeout
MiP: Response timeout
MiP: Response timeout
MiP: Response timeout
```

**Comment by Tiogaplanet** [comment]
I did not experience that problem with cage but I did experience it with roam.  On the bench EnableGameMode.ino worked fine with MiP face down (I can't find a kickstand right now) but it wouldn't come out of roam mode while testing on the floor.  You can see in [EnableGameMode.ino](https://github.com/Tiogaplanet/MiP_ProMini-Pack/blob/SetGameModes/Arduino/MiP_ProMini_Pack_Library/examples/EnableGameMode/EnableGameMode.ino#L70) that I had to add a stop command at line 70 to get MiP to come out of roam mode while testing.  

If the same fix is needed for cage mode then each of the new enable mode functions might need a quick edit to add a call to `stop()` before enabling the new mode.

Out of curiosity, which sw and hw versions do you have?  I have three MiPs but I only use one for programming at the moment.

```
software version: 2014-3-22.2
hardware info
  voice chip version: 9
  hardware version: 1
```

**Comment by adamgreen** [comment]
My version information matches.

I hadn't tried running the code when it was face down. When I did that, I saw the expected serial output.

When running on the floor, it was switching modes but not sending back the expected serial output because the **bool** returning mode querying functions were always timing out.

I added commit 00cccf379dc3d3f9cd9f468db7f9812cec2ee9ad to work around this issue. The raw set/get commands now issue a stop() first and the getter restarts the current game mode by calling the raw setter again at the end once it has successfully issued the get.

**Comment by adamgreen** [comment]
@Tiogaplanet What do you think about updating the documentation to describe what the MiP does in each game mode? For example, the description for enableCageMode() could be extended a bit to be more like, "Place MiP in cage mode. The MiP will **...** when in this mode."

**Comment by adamgreen** [comment]
PS: Thanks so much for adding this new functionality. Much appreciated!

**Comment by Tiogaplanet** [comment]
I'll have another go at the documentation to make it more complete.

**Comment by adamgreen** [comment]
> I'll have another go at the documentation to make it more complete.

Thanks!

**Pull request merged**
